"""set user email to required.

Revision ID: 214cb02199f0
Revises: f1cf97e169d0
Create Date: 2024-02-27 11:27:15.830892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '214cb02199f0'
down_revision = 'f1cf97e169d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)

    # ### end Alembic commands ###
