"""added user favourite city model.

Revision ID: 555a213b3b5d
Revises: 96a20e2c105f
Create Date: 2024-02-26 10:13:19.872922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '555a213b3b5d'
down_revision = '96a20e2c105f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favourite_cities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favourite_cities',
    sa.Column('id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=32), nullable=False),
    sa.Column('city', sa.VARCHAR(length=150), nullable=False),
    sa.Column('latitude', sa.FLOAT(), nullable=True),
    sa.Column('longitide', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###
